# config/packages/rate_limiter.yaml

framework:
    rate_limiter:

        # ======================================================
        # VOTES ANONYMES (GUESTS)
        # ======================================================
        # Règle métier : max 5 votes par invité toutes les 24h
        vote_guest:
            policy: sliding_window
            limit: 5
            interval: '24 hours'          
            # cache_pool: cache.app         # On peut passer à Redis plus tard

        # ======================================================
        # INSCRIPTION (anti-spam / bots)
        # ======================================================
        registration:
            policy: fixed_window
            limit: 4
            interval: '1 hour'

        # ======================================================
        # SIGNALEMENTS (éviter les abus)
        # ======================================================
        # report:
        #     policy: sliding_window
        #     limit: 10
        #     interval: '1 hour'